Magickbase/godwoken_explorer

config/test.exs, lib/godwoken_explorer/application.ex, test/godwoken_explorer/block_test.ex, test/support/data_case.ex, test/support/factory.ex, test/test_helper.exs
=> test: add test framework

lib/godwoken_explorer/account.ex
链上回滚会出现两个account id不一样，但是 script hash 是一样的，这时候需要重新fetch 一下account 数据
=> feat:handle account rollbabck cause script hash not match bug

lib/godwoken_indexer/block/bind_l1_l2_worker.ex, lib/godwoken_indexer/block/sync_deposition_worker.ex
=> feat: add sync deposition worker

lib/godwoken_explorer/account.ex, lib/godwoken_explorer_web/controllers/api/search_controller.ex
=> feat: use ckb args can find layer2 account

lib/godwoken_explorer/udt.ex
=> fix: add unique constraint

lib/godwoken_explorer_web/controllers/api/search_controller.ex
=> feat: search pending tx

lib/godwoken_explorer/pending_transaction.ex, lib/godwoken_explorer_web/channels/transaction_channel.ex
=> feat: response may return nil

lib/godwoken_indexer/block/sync_l1_block_worker.ex
=> chore: adjust buffer block number

lib/godwoken_explorer/withdrawal_history.ex, lib/godwoken_indexer/block/global_state_worker.ex
=> eat: update withdrawal history available state

lib/godwoken_explorer_web/views/withdrawal_history_view.ex
=> feat: transfrom available to succeed

lib/godwoken_explorer_web/channels/transaction_channel.ex
=> fix: match empty map

lib/godwoken_explorer/pending_transaction.ex
=> fix: short address may be nil

lib/godwoken_explorer_web/controllers/api/udt_controller.ex, lib/godwoken_explorer_web/views/udt_view.ex
=> feat: filter udt by type

lib/godwoken_explorer_web/views/udt_view.ex
=> feat: show icon for udt api

lib/godwoken_explorer_web/views/udt_view.ex
=> fix: query select icon

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/udt.ex, lib/godwoken_explorer_web/controllers/api/search_controller.ex
=> feat: search udt

lib/godwoken_explorer_web/controllers/api/udt_controller.ex, lib/godwoken_explorer_web/views/udt_view.ex
=> feat: return udt account detail for udt detail api

lib/godwoken_explorer_web/controllers/api/udt_controller.ex, lib/godwoken_explorer_web/views/udt_view.ex
=> feat: return type script

lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/transaction_controller.ex
=> feat: filter by contract address

.github/ISSUE_TEMPLATE/register-a-general-contract.md, .github/ISSUE_TEMPLATE/register-a-new-bridged-token.md, .github/ISSUE_TEMPLATE/register-a-new-native-erc20-token.md
Add issue templates to register bridged tokens and native erc20 tokens
=> chore: add two templates to register tokens

lib/godwoken_explorer/transaction.ex
This reverts commit 50b0a482697ca1da75f97bc02c3a73e5beceae44.
=> refactor: account txs query

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/account_udt.ex, lib/godwoken_explorer_web/controllers/api/account_controller.ex, lib/godwoken_rpc/util.ex
=> feat: fetch all udt balance realtime

lib/godwoken_explorer/chain/cache/transaction_count.ex
=> feat: change transaction cache count

lib/godwoken_explorer/account_udt.ex
=> feat: filter balance is zero of account udt

lib/godwoken_explorer/account_udt.ex
=> fix: use enum reject

lib/godwoken_explorer_web/controllers/api/withdrawal_history_controller.ex, lib/godwoken_explorer_web/views/withdrawal_history_view.ex
=> feat: support l2_script_hash query of withdrawal histroy

lib/godwoken_explorer/account.ex, lib/godwoken_indexer/block/sync_l1_block_worker.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/block.ex
=> feat: handle withdraw_request empty

lib/godwoken_explorer/account.ex
=> fix: id to string

config/dev.per.exs, lib/godwoken_explorer/pending_transaction.ex, lib/godwoken_rpc/godwoken_rpc.ex
=> feat: query mempool tx by node

lib/godwoken_explorer/account.ex, lib/godwoken_indexer/block/sync_l1_block_worker.ex
=> feat: fix script_hash not match account id

priv/repo/migrations/20220117121117_add_block_number_index_to_blocks.exs
=> chore: add block number index to transactions

lib/godwoken_explorer/account.ex
=> feat: handle udt nil

lib/godwoken_explorer/account.ex
=> feat: manual create account dont trigger broadcast

lib/godwoken_explorer_web/controllers/api/transaction_controller.ex
=> fix: struct to map

lib/godwoken_rpc/withdrawal_request.ex
=> fix: withdrawal request get udt_id from UDT

lib/godwoken_explorer_web/controllers/api/fallback_controller.ex, lib/godwoken_explorer_web/controllers/api/transfer_controller.ex, lib/godwoken_explorer_web/views/error_view.ex, test/godwoken_explorer_web/controllers/api/transfer_controller_test.exs, test/godwoken_explorer_web/views/error_view_test.exs
=> fix: return error when account not exist

lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/transfer_controller.ex
=> feat: contract address should return erc20 txns

lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex
=> feat: return type

lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex
=> feat: add timestamp of withdrawal

lib/godwoken_explorer_web/controllers/api/deposit_withdrawal_controller.ex, lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex, test/godwoken_explorer_web/controllers/deposit_withdrawal_controller_test.exs
=> feat: deposit and withdrawal list by block_number or udt_id

lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex, test/godwoken_explorer_web/controllers/deposit_withdrawal_controller_test.exs
=> feat: use union all merge deposit and withdrawals

lib/godwoken_explorer/polyjuice.ex
=> feat: insert polyjuice on_conflict nothing

lib/godwoken_explorer/polyjuice.ex, lib/godwoken_explorer/withdrawal_request.ex, priv/repo/migrations/20220120071916_create_polyjuice_unique_index.exs
=> feat: update unique index

lib/godwoken_explorer/udt.ex, lib/godwoken_explorer_web/views/udt_view.ex
=> feat: return description and official_site of udt

lib/godwoken_explorer_web/views/udt_view.ex
=> fix: reutrn type script of udt

lib/godwoken_explorer/account.ex
=> feat: return icon of account detail

lib/godwoken_explorer_web/views/withdrawal_history_view.ex
=> fix: nested udt preload

lib/godwoken_explorer/account.ex, lib/godwoken_explorer_web/views/udt_view.ex, lib/godwoken_rpc/util.ex
=> fix: decimal to string normal type

config/prod.exs
=> chore: update check_origin configuration

config/prod.exs
=> chore: update origin

lib/godwoken_explorer_web/controllers/api/deposit_withdrawal_controller.ex, lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex, test/godwoken_explorer_web/controllers/deposit_withdrawal_controller_test.exs
=> feat: get withdrawal data from withdrawal history

lib/godwoken_explorer/transaction.ex
=> feat: limit tx account for performance

lib/godwoken_explorer/transaction.ex
=> fix: sort use block_nubmer first

lib/godwoken_explorer/transaction.ex
=> feat: all tx query sort by block_nubmer first

lib/godwoken_explorer/transaction.ex
=> fix: should pass tx_hash not map

lib/godwoken_explorer/transaction.ex
=> fix: bridge account id may nil

lib/godwoken_explorer/transaction.ex
=> feat: use union_all

lib/godwoken_explorer/transaction.ex
=> fix: query by tx_hashes wrong order

lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer/udt.ex
=> fix: udt tx account

lib/godwoken_explorer_web/controllers/api/account_controller.ex, lib/godwoken_explorer_web/controllers/api/search_controller.ex
=> feat: remove account_id search

lib/godwoken_explorer/transaction.ex
=> fix: return inserted_at as timestamp

lib/godwoken_explorer/transaction.ex, test/godwoken_explorer_web/controllers/api/transaction_controller_test.exs
=> fix: show udt by bridge account id

lib/godwoken_explorer/udt.ex
=> fix: bridge account udt decimal

lib/godwoken_explorer/polyjuice_creator.ex, priv/repo/migrations/20220125114647_add_unique_index_to_polyjuice_creators.exs
=> fix: add unique index for polyjuice creators

lib/godwoken_rpc/godwoken_rpc.ex
=> fix: gas_used hex to number

lib/godwoken_explorer/block.ex, lib/godwoken_explorer_web/channels/block_channel.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex
=> feat: update block api

lib/godwoken_explorer_web/channels/block_channel.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex
=> feat: return block size

lib/godwoken_explorer_web/channels/block_channel.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex
=> feat: return parent_hash

config/test.exs, lib/godwoken_explorer/block.ex, lib/godwoken_explorer/transaction.ex, test/godwoken_explorer_web/controllers/api/transaction_controller_test.exs, test/support/factory.ex
=> feat: use polyjuice_status as key

lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex
=> fix: when udt decimal is nil use 0

lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex
=> fix: when withdrawal history udt decimal is nil use 0

config/stg.exs, lib/godwoken_explorer_web/endpoint.ex, rel/config.exs
=> chore: rename mix env staging to stg

lib/godwoken_explorer/udt.ex
=> fix: save supply after div

lib/godwoken_explorer/block.ex, lib/godwoken_explorer_web/channels/block_channel.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex, lib/godwoken_explorer_web/controllers/api/udt_controller.ex, lib/godwoken_explorer_web/router.ex, lib/godwoken_explorer_web/views/block_view.ex, lib/godwoken_indexer/block/global_state_worker.ex, lib/godwoken_rpc/util.ex, test/godwoken_explorer_web/controllers/api/block_controller_test.exs, test/support/factory.ex
=> feat: block list api

lib/godwoken_explorer_web/controllers/api/search_controller.ex
=> fix: serach api block struct

lib/godwoken_explorer_web/controllers/api/udt_controller.ex, test/godwoken_explorer_web/controllers/api/udt_controller_test.exs, test/support/factory.ex
=> feat: support udt script hash api

lib/godwoken_explorer_web/controllers/api/udt_controller.ex
=> fix: missing result variable

lib/godwoken_explorer_web/controllers/api/udt_controller.ex
=> fix: action callback

lib/godwoken_indexer/block/sync_worker.ex
=> fix: uncomment trigger account

lib/godwoken_indexer/block/sync_worker.ex
=> fix: missing block columns in transactions

lib/godwoken_indexer/block/sync_worker.ex
=> fix: return block_hash for get transaction timestamp

lib/godwoken_explorer_web/controllers/api/transfer_controller.ex
=> fix: change arguments hash style

lib/godwoken_explorer/block.ex
=> refactor: query tx by block hash

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/udt.ex, lib/godwoken_explorer_web/controllers/api/transfer_controller.ex
=> feat: use token_transfers data as transfer api data source

lib/godwoken_explorer/token_transfer.ex
=> fix: return original value when udt unknown

lib/godwoken_explorer/token_transfer.ex
=> fix: parse integer to string

lib/godwoken_explorer/token_transfer.ex
=> fix: sql case when

lib/godwoken_indexer/block/sync_worker.ex
=> fix: home txs data no order

lib/godwoken_explorer/chain/cache/transaction_count.ex, lib/godwoken_explorer/transaction.ex
=> refactor: enhance latest 10 tx records

priv/repo/migrations/20220227154044_add_block_number_index_to_transaction.exs
=> feat: add block number index to transactions

lib/godwoken_explorer/transaction.ex
=> fix: sort by block_number and inserted_at

lib/godwoken_explorer/transaction.ex
=> fix: inserted_at

lib/godwoken_rpc/account/fetched_balance.ex
=> fix: rename value to balance

lib/godwoken_rpc/transaction.ex
=> fix: transfer native token method id

lib/godwoken_explorer/account_udt.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/transaction.ex
=> fix:filter nil short_address

lib/godwoken_explorer/token_transfer.ex
=> feat: return more column for transfer api

lib/godwoken_explorer/token_transfer.ex
=> fix: nonce by transaction

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/account_udt.ex, lib/godwoken_explorer/block.ex, lib/godwoken_explorer/check_info.ex, lib/godwoken_explorer/contract_method.ex, lib/godwoken_explorer/deposit_history.ex, lib/godwoken_explorer/log.ex, lib/godwoken_explorer/pending_transaction.ex, lib/godwoken_explorer/polyjuice.ex, lib/godwoken_explorer/polyjuice_creator.ex, lib/godwoken_explorer/smart_contract.ex, lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer/udt.ex, lib/godwoken_explorer/udt_transfer.ex, lib/godwoken_explorer/version.ex, lib/godwoken_explorer/withdrawal_history.ex, lib/godwoken_explorer/withdrawal_request.ex
=> fix smart contract access error

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer_web/controllers/api/transfer_controller.ex, test/godwoken_explorer_web/controllers/api/transfer_controller_test.exs
=> feat: list token transfer by tx_hash

docs/godwoken_configuration.md
=> docs: godwoken configuration detail

lib/godwoken_explorer/account_udt.ex
=> fix: find account_udt by address_hash and token_contract_address_hash

lib/godwoken_explorer/transaction.ex
=> feat: query tx no need join polyjuice

lib/godwoken_explorer/transaction.ex
=> feat: refactor list transaction tx_hash by condition

lib/godwoken_explorer/account.ex, lib/godwoken_indexer/block/sync_l1_block_worker.ex
=> feat: remove ckb_lock_hash of account

lib/godwoken_indexer/block/sync_worker.ex
=> fix: remove unused recieve_address

lib/godwoken_explorer_web/views/udt_view.ex
=> feat: cal token holder by token_contract_address_hash

lib/godwoken_explorer_web/views/udt_view.ex
=> fix: add bridge_account_id

priv/repo/migrations/20220308152742_add_inserted_at_index_to_token_transfers.exs
=> feat: add inserted_at index to token_transfers

config/dev.exs, config/dev.per.exs, config/prod.exs, config/stg.exs, lib/godwoken_explorer_web/endpoint.ex, mix.exs
=> chore: remove appsignal

lib/godwoken_explorer/transaction.ex
=> feat: add account_id with many txs

config/prod.exs
=> chore: update endpoint config

lib/godwoken_explorer/token_transfer.ex
=> feat: handle huge data token_transfer address

lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/transaction_controller.ex
=> feat: add paging options to tx api

lib/godwoken_explorer_web/controllers/api/smart_contract_controller.ex, lib/godwoken_explorer_web/router.ex, lib/godwoken_explorer_web/views/smart_contract_view.ex
=> feat: list smart contract

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex
=> feat: add huge data account_id

lib/godwoken_explorer/transaction.ex
=> feat: update user huge data account id

lib/godwoken_explorer/account.ex
=> feat: show polyjuice contract udt

lib/godwoken_explorer/block.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/util.ex
=> feat: use block timestamp inserted of inserted_at

lib/godwoken_explorer/block.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/util.ex
=> revert block timestamp

lib/godwoken_explorer/transaction.ex
=> feat: user tx order by nonce

lib/godwoken_explorer/application.ex, lib/godwoken_explorer/chain.ex, lib/godwoken_explorer/counters/average_block_time.ex
=> feat: latest block average block time

lib/godwoken_explorer/counters/average_block_time.ex
=> fix: refresh average timestamp period

lib/godwoken_explorer/daily_stat.ex
=> feat: block timestamp less than end_time

priv/repo/migrations/20220323113916_add_unique_index_to_key_values.exs
=> feat: add unqiue index of key_values key

lib/godwoken_explorer/token_transfer.ex
=> feat: update huge data account of token transfer

lib/godwoken_explorer/udt.ex
=> feat: compare time use ==

lib/godwoken_explorer/udt.ex
=> fix: value is nil condition

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex
=> feat: set unique order

lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/godwoken_rpc.ex, lib/godwoken_rpc/transaction.ex
=> refactor: sync worker

lib/godwoken_explorer/token_transfer.ex
=> fix: udt join

lib/godwoken_explorer/token_transfer.ex
eg: 0x000000000000000000000000000000000000dead
=> feat: token transfer to address may not exist

config/deploy.rb
=> chore: update github repo url

lib/godwoken_explorer/transaction.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/transaction.ex
=> feat: handle unknown tx type

lib/godwoken_explorer/counters/address_token_transfers_counter.ex, lib/godwoken_explorer/token_transfer.ex
=> feat: set non-exist account's token transfer count

lib/godwoken_explorer_web/controllers/api/search_controller.ex
=> fix: cond missed true condition

README.md
=> docs: udpate readme

priv/repo/migrations/20220407033927_change_udt_description_type.exs
=> feat: change udt description type

lib/godwoken_explorer/account_udt.ex
=> feat: add udt type

lib/godwoken_explorer/chain.ex
=> feat: add account transaction count type

lib/godwoken_explorer/account.ex
=> fix: create account timeout

lib/godwoken_indexer/block/sync_worker.ex
=> feat: fetch multip block once

lib/godwoken_explorer/account_udt.ex
=> feat: fix udt nil cause error

lib/godwoken_explorer/graphql/resolovers/log.ex, lib/godwoken_explorer/graphql/resolovers/token_transfer.ex, lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex, priv/repo/migrations/20220415065517_remove_unused_indexs.exs
=> feat: update index and update order by

lib/godwoken_explorer/transaction.ex
=> feat: return transaction_index for display

config/prod.exs, lib/godwoken_explorer/token_transfer.ex
1. log rotate
2. token_transfer 限制最近3天如果数据量过大
=> Log rotate

lib/godwoken_explorer/token_transfer.ex
PG query count is very slow for large data.So don't query count every time if the count is out of limit.
=> feat: use custom total_entries

lib/godwoken_explorer/token_transfer.ex
=> fix: udt address transfer query condition

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex
=> feat: use custom total_entries for transaction

lib/godwoken_explorer/token_transfer.ex
=> fix: nil paging_options

lib/godwoken_explorer_web/controllers/admin/udt_controller.ex, lib/godwoken_explorer_web/templates/admin/udt/index.html.eex
=> fix: udt_params[id] is nil

lib/godwoken_indexer/block/supervisor.ex
=> fix: remove comment

lib/godwoken_explorer/account_udt.ex
=> fix: default transction_count 0

lib/godwoken_explorer/account_udt.ex
=> fix: missed tx count

lib/godwoken_explorer/repo.ex
ref: https://stackoverflow.com/questions/21385555/postgresql-query-very-slow-with-limit-1
Pg for limit have a bug
Solution:
1.  add a unneed order by column
2.  adjust limit size
=> feat: default page_size: 20

lib/godwoken_explorer/block.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/util.ex
=> feat: use block timestamp

lib/godwoken_explorer/transaction.ex
=> feat: manual control pg use from_account_id index

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/udt.ex, lib/godwoken_indexer/worker/copy_yok_contract.ex, lib/godwoken_indexer/worker/import_contract_code.ex
自动识别bytecode是否和yok 的一样，如果一样就创建一份合约
=> feat: generate contract that byte code same as yok

lib/godwoken_explorer/token_transfer.ex
v1 没有 user， 只有eth_user 和 tron_user 类型
=> fix: filter by eth_user for token_transfer

lib/godwoken_indexer/block/sync_worker.ex
tx account's nonce need to add 1
=> feat: tx nonce should add 1 because of first is 0

lib/godwoken_explorer_web/views/smart_contract_view.ex
=> fix: missing limit import

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/smart_contract.ex, lib/godwoken_explorer_web/views/smart_contract_view.ex
=> feat: show contract creator address in account api

lib/godwoken_explorer/transaction.ex
=> feat: return created_contract_address_hash if tx is deploy contract type

lib/godwoken_explorer/account_udt.ex, lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/views/deposit_withdrawal_view.ex, lib/godwoken_rpc/util.ex
=> feat: cal balance with decimal

lib/godwoken_rpc/block.ex
=> fix: fetch_eth_block_by_hash may return nil, so let it crash

lib/godwoken_rpc/block.ex
=> fix: missed 0x for producer_address

lib/godwoken_explorer/molecule_parser.ex, lib/godwoken_indexer/block/sync_l1_block_worker.ex, native/molecule_parser/src/lib.rs
=> fix: parse v1 deposit lock args

lib/godwoken_explorer/application.ex, lib/godwoken_explorer/chain/cache/poly_version.ex, lib/godwoken_explorer_web/controllers/api/poly_version_controller.ex, lib/godwoken_explorer_web/router.ex, lib/godwoken_rpc/godwoken_rpc.ex, lib/godwoken_rpc/web3/fetched_poly_version.ex
=> feat: cache poly version

lib/godwoken_explorer/chain/cache/poly_version.ex
=> feat: cache poly version no expired

.github/workflows/prod_mainnet v1.yml
=> chore: add github workflow

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer/udt.ex
=> fix: add prefix 0x for fragment encode hex

config/chains/testnet_v1_1.exs, lib/godwoken_explorer/udt.ex
=> feat: import udt from github

lib/godwoken_explorer/chain/exporter/transaction_csv.ex, lib/godwoken_explorer/token_transfer.ex
1. polyjuice status and block status return for transaction csv
2. when token_transfer count is 0, return []
=> fix:: export csv bug

lib/godwoken_explorer/chain.ex, lib/godwoken_explorer_web/controllers/api/account_controller.ex
=> fix: show account by script hash

lib/godwoken_explorer/transaction.ex
=> fix: missed to_string for polyjuice input

lib/godwoken_explorer/account/current_udt_balance.ex
=> fix: decimal not exist is 0

lib/godwoken_explorer/account/udt_balance.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_indexer/fetcher/udt_balance.ex, lib/godwoken_rpc/util.ex
=> feat: change current udt balance timestamps type

lib/godwoken_explorer/account/current_udt_balance.ex
=> feat: total suplly may be 0

lib/godwoken_rpc/godwoken_rpc.ex, lib/godwoken_rpc/transaction/get_gw_tx_by_eth_tx.ex
=> feat: get gw tx hash by eth hash

docs/schema.graphql, lib/godwoken_explorer/graphql/resolovers/account.ex, lib/godwoken_explorer/graphql/types/account.ex, test/graphql/account_test.exs, test/graphql/account_udt_test.exs
link issue:
https://github.com/Magickbase/godwoken_explorer/issues/788
=> Feat: add bridged udt for account subfield query

docs/schema.graphql, lib/godwoken_explorer/graphql/resolovers/account_udt.ex, lib/godwoken_explorer/graphql/types/account_udt.ex
fix this issue https://github.com/Magickbase/godwoken_explorer/issues/795
=> Fix: fix account udts api with u.contract_address_hash for join on

docs/schema.graphql, lib/godwoken_explorer/graphql/types/block.ex, test/graphql/account_test.exs, test/graphql/account_udt_test.exs, test/graphql/block_test.exs, test/graphql/log_test.exs, test/graphql/smart_contract_test.exs, test/graphql/token_transfers_test.exs, test/graphql/transaction_test.exs, test/graphql/udt_test.exs
cherry pick from https://github.com/Magickbase/godwoken_explorer/pull/791
=> mainnet Feat: add graphql testing

docs/schema.graphql, lib/godwoken_explorer/graphql/resolovers/account_udt.ex, lib/godwoken_explorer/graphql/types/account_udt.ex
copy from https://github.com/Magickbase/godwoken_explorer/pull/797/files
=> Mainet Fix: fix account udts api with u.contract_address_hash for join on

docs/schema.graphql, lib/godwoken_explorer/graphql/resolovers/account.ex, lib/godwoken_explorer/graphql/types/account.ex, test/graphql/account_test.exs, test/graphql/account_udt_test.exs
copy from https://github.com/Magickbase/godwoken_explorer/pull/792
=> Mainnet Feat: add bridged udt for account subfield query

lib/godwoken_explorer/token_transfer.ex, test/godwoken_explorer_web/controllers/api/transfer_controller_test.exs
如果一个tx_hash下没有token_transfer, 之前的sql 查询会返回全部的transfer，导致504，修复这个bug
=> fix: if no records return []

lib/godwoken_explorer/log.ex, lib/godwoken_explorer/token/metadata_retriever.ex
=> fix: change functions info return keys

lib/godwoken_explorer/account/udt_balance.ex, lib/godwoken_explorer/chain/exporter/token_holder_csv.ex, lib/godwoken_explorer_web/controllers/api/snapshot_controller.ex, lib/godwoken_explorer_web/router.ex, test/factories/udt_balance_factory.ex, test/godwoken_explorer_web/controllers/api/snapshot_controller_test.exs, test/support/factory.ex
=> feat: export snapshot through api

docs/schema.graphql, lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/graphql/types/udt.ex, test/graphql/udt_test.exs
copy from https://github.com/Magickbase/godwoken_explorer/pull/824
=> Mainnet Copy PR: enhancement for issue 823, add query condition for udt

lib/godwoken_explorer/graphql/middleware/null_filter.ex, lib/godwoken_explorer/graphql/resolovers/token_transfer.ex, lib/godwoken_explorer/graphql/types/token_transfer.ex, test/graphql/token_transfers_test.exs
copy from https://github.com/Magickbase/godwoken_explorer/pull/830
=> Mainnet Copy PR: fix issue 827 with filtering unused input field witch value is null

lib/godwoken_explorer/graphql/resolovers/smart_contract.ex, lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_explorer/graphql/schemas/graphql.ex, lib/godwoken_explorer/graphql/types/custom/chain_data.ex, lib/godwoken_explorer/graphql/types/polyjuice.ex, lib/godwoken_explorer/graphql/types/transaction.ex, lib/godwoken_explorer/polyjuice.ex, test/graphql/transaction_test.exs
example:
```graphql
query {
transaction(
input: {
eth_hash: "0x95e7769948e6dacd8074ec37371c72cad0a9b7fd1897594a79c0c3ee7873e062"
}
) {
hash
from_account_id
to_account_id
method_id
method_name
polyjuice {
input
}
}
}
```
result
```graphql
{
"data": {
"transaction": {
"from_account_id": 83,
"hash": "0x6de01cae85c20d1ee0f4c651bcc68069edd7386f1f0c12c71fc91ff44d852f3e",
"method_id": "0x60806040",
"method_name": null,
"polyjuice": {
"input": "0x608060405234801561001057600080fd5b50604051610e30380380610e308339810180604052810190808051906020019092919080518201929190602001805190602001909291908051820192919050505083600160003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508360008190555082600390805190602001906100b29291906100ee565 …
```
=> feat-762: add method id and method name for transction object

.iex.exs, config/config.exs, lib/godwoken_explorer/account.ex, lib/godwoken_explorer/graphql/workers/smart_contract_register.ex
re-implement the smart contract auto register work by registering the ployjuice contract account which not registered in smart contract table.
the worker will be working per minute
=> Feat: add SmartContractRegister auto worker

lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/transaction_controller.ex, lib/godwoken_rpc/util.ex
Reverts Magickbase/godwoken_explorer#938
=> Revert "Issue 802 2"

lib/godwoken_rpc/util.ex
=> fix: set default datetime

lib/godwoken_rpc/util.ex
Reverts Magickbase/godwoken_explorer#941
=> Revert "fix: set default datetime"

.github/ISSUE_TEMPLATE/register-a-general-contract.yml, .github/ISSUE_TEMPLATE/register-a-new-bridged-token.yml, .github/ISSUE_TEMPLATE/register-a-new-native-erc20-token.yml
1. add a link to sourcify for contract source code verification
2. remove useless fields in form of registering native erc20 tokens
=> chore: update issue templates of registering tokens

lib/godwoken_explorer/account/current_udt_balance.ex, test/godwoken_explorer_web/controllers/api/rpc/account_controller_test.exs
Today update all token type caused
=> fix: sort with value_fetched_at

lib/godwoken_explorer/graphql/resolovers/transaction.ex, test/graphql/transaction_test.exs
link https://github.com/Magickbase/godwoken_explorer/issues/894
=> Fix: change 0x data to nil of method id

lib/godwoken_indexer/transform/token_approvals.ex
```
[error] GenServer #PID<0.28448.0> terminating
** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
from t0 in GodwokenExplorer.TokenApproval,
where: t0.token_owner_address_hash == ^"0x02fe5abfc9054c9e23b47c7743ee6f55b35e8470" and
t0.token_contract_address_hash == ^"0xd5df1fc4b438c2b1441988dec329dca193637307" and
t0.data == ^0 and t0.type == ^:approval and t0.approved == ^true
(ecto 3.7.1) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3
(godwoken_explorer 0.1.0) lib/godwoken_indexer/transform/token_approvals.ex:21: anonymous fn/1 in GodwokenIndexer.Transform.TokenApprovals.parse/1
(elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
(godwoken_explorer 0.1.0) lib/godwoken_indexer/transform/token_approvals.ex:17: …
```
=> fix: token approval exist multiple results

lib/godwoken_explorer/token_approval.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_indexer/transform/token_approvals.ex, lib/godwoken_indexer/transform/token_transfers.ex, priv/repo/migrations/20220928024409_add_token_type_to_token_approval.exs, priv/repo/migrations/20220928024844_alter_index_to_token_approval.exs, test/godwoken_indexer/transform/token_approvals_test.exs
- For erc20 approval event， only：  [:token_owner_address_hash, :spender_address_hash,:token_contract_address_hash] is uniq
- For erc721 approval envet, only: [:token_owner_address_hash,:token_contract_address_hash, :token_id]  is uniq
- For approval_all event, only: [:token_owner_address_hash,:token_contract_address_hash] is uniq
- After transfer erc721, token approval record will delete
- unit test
- none
=> Issue 1014

lib/godwoken_rpc/transaction.ex, lib/godwoken_rpc/util.ex, test/godwoken_rpc/util_test.exs
=> ftest: parse_polyjuice_args util

lib/godwoken_explorer/account/current_udt_balance.ex, lib/godwoken_explorer/counters/average_block_time.ex
=> fix: datetime sort_by must use DateTime.compare/2 to compare

lib/godwoken_explorer/counters/average_block_time.ex
Increase calculate average_block_time used block count to 200.
- none
- none
=> Increase average block time count

lib/godwoken_explorer/smart_contract.ex, priv/repo/migrations/20221017052340_add_account_id_unique_index_to_smart_contract.exs
Souricy worker will insert all smart_contracts to table.So we need a uniq index to avoid other operation insert same records.
- none
- none
=> Issue 1091

.github/workflows/test.yml, lib/godwoken_explorer/account.ex, lib/godwoken_indexer/worker/generate_erc20_series_contract.ex, lib/godwoken_indexer/worker/generate_yok_series_contract.ex, lib/godwoken_indexer/worker/import_contract_code.ex, test/godwoken_indexer/worker/generate_erc20_series_contract_test.exs
When we insert smart contract, it may already exist. So we need to update.
- unit test
- none
=> Issue 1079

README.md
link: #1039 
update readme by adding graphql api docs link
check github readme info with  graphql api docs link
- unit test
- none
=> Docs: Issue 1039 api docs

lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/graphql/types/udt.ex, lib/godwoken_explorer/udt.ex, priv/repo/migrations/20221108083958_add_uan_and_display_name_to_ud_ts.exs, test/factories/udt_factory.ex, test/graphql/account_test.exs, test/graphql/udt_test.exs
To divide contract's name symbol with bridge token's uan and display_name.Because we may update name and symbol by read from contract.
- unit test
- none
=> Issue 1132

test/godwoken_explorer/account_test.exs
=> test: add test

lib/godwoken_rpc/block.ex
Hotfix when rpc failed return nil value.
- none
- none
=> Issue 1151

lib/godwoken_rpc/block.ex
Reverts Magickbase/godwoken_explorer#1152
=> Revert "Issue 1151"

lib/godwoken_indexer/block/sync_worker.ex
Filter failed transaction when create contract account
- unit test
- none
=> fix: filter failed polyjuice transaction

lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/graphql/schemas/graphql.ex, test/graphql/udt_test.exs
link issue #1134 
feat: fix null input value panic error when calling `udt` api
- check `udt` api
- unit test
- none
=> feat: fix null input value panic error (issue-1134)

.dockerignore, .github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/prod_mainnet v1.yml, .github/workflows/prod_mainnet.yml, .github/workflows/prod_testnet.yml, .github/workflows/prod_testnet_v1_1.yml, .github/workflows/staging_testnet_v1_1.yml, .gitignore
The workflows will build docker image of gwscan and push to github repository
Then the workflows will update image info on K8S and restart the workload
- unit test
- none
=> GitHub actions deploy to k8s

lib/godwoken_explorer/graphql/resolovers/log.ex, lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_explorer/graphql/types/log.ex, lib/godwoken_explorer/graphql/types/smart_contract.ex, lib/godwoken_explorer/smart_contract.ex, test/graphql/log_test.exs, test/graphql/sourcify_test.exs
link #1140 
- log api
- logs api
- unit test
- none
=> Feat:  update log/logs api with cursor-base paginator and contract subobject  Issue 1140

lib/godwoken_explorer/transaction.ex
Query latest 10 transactions direct from transaction table.
- unit test
- none
=> feat: query latest 10 transactions from transaction table

lib/godwoken_explorer/graphql/dataloader/graphql_ecto.ex, lib/godwoken_explorer/graphql/dataloader/transaction.ex, lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_explorer/graphql/schemas/graphql.ex, lib/godwoken_explorer/graphql/types/transaction.ex, lib/godwoken_explorer/transaction.ex
link issue #1114 
solve n+1 problem(multiple query for the subfeild) for `transaction object` subfield resolver
and optimize the `transactions` api
check all api(transaction/transactions) with transaction object 
- polyjuice subfield
- polyjuice_creator subfield
- from_account subfield
- to_account subfield
- block subfield
- unit test
- none
=> Feat: add dataloader for trsanction object Issue 1114

lib/godwoken_explorer/block.ex
Update blocks finalized state cause database timeout.So add timeout infinity to avoid it.
- none
- none
=> Issue 1190

lib/godwoken_explorer/block.ex
Refactor code to avoid update block state caused database preformance
- none
- none
=> refactor: uset block's state finalized

lib/godwoken_explorer/udt.ex
link issue #1164 
- unit test
- none
=> Fix: fix check erc721/erc1155 interface (issue-1164)

lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_indexer/block/pending_transaction_worker.ex, lib/godwoken_rpc/godwoken_rpc.ex
when tx hash not exist in our db, query it from fullnode
- none
- none
=> feat: when tx hash not exist in our db, query it from fullnode

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/block.ex, lib/godwoken_indexer/block/pending_transaction_worker.ex, lib/godwoken_indexer/block/sync_worker.ex, test/godwoken_indexer/block/pending_transaction_worker_test.exs
When pending_transaction worker rpc failed ,ignore it and retry
- unit test
- none
=> Issue 1211

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/block.ex, lib/godwoken_explorer_web/sentry_filter.ex, lib/godwoken_indexer/block/pending_transaction_worker.ex, lib/godwoken_indexer/block/sync_worker.ex, test/godwoken_indexer/block/pending_transaction_worker_test.exs
=> Godwoken v1 testnet prod

.github/workflows/prod_mainnet v1.yml, .github/workflows/prod_testnet_v1_1.yml, .github/workflows/staging_testnet_v1_1.yml
graphiql env set wrong before.
- unit test
- none
=> chore: set graphiql env for each docker deploy environment

lib/godwoken_explorer/graphql/resolovers/smart_contract.ex, test/graphql/smart_contract_test.exs
issue link: #1214 
fix raise error when call smart_contracts api with cursor of null field(name field of smart_contract
- smart_contracts api with cursor field of name
- unit test
- none
=> Bug: fix raise error when call smart_contracts api with cursor of null field(name field of smart_contract) issue-1214

lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/graphql/types/udt.ex, lib/godwoken_explorer/udt.ex, test/graphql/udt_test.exs
link #481 
add rank for udts/erc721_udts/erc1155_udts api
- `udts` api with rank number
- `erc721_udts` api with rank number
- `erc1155_udts` api with rank number
- unit test
- none
=> feat: add rank number for udts/erc721_udts/erc1155_udts

.iex.exs, docs/schema.graphql, lib/godwoken_explorer/account/current_udt_balance.ex, lib/godwoken_explorer/block.ex, lib/godwoken_explorer/chain.ex, lib/godwoken_explorer/graphql/dataloader/batch_polyjuice.ex, lib/godwoken_explorer/graphql/dataloader/batch_udt.ex, lib/godwoken_explorer/graphql/dataloader/smart_contract.ex, lib/godwoken_explorer/graphql/resolovers/account.ex, lib/godwoken_explorer/graphql/resolovers/block.ex, lib/godwoken_explorer/graphql/resolovers/polyjuce.ex, lib/godwoken_explorer/graphql/resolovers/smart_contract.ex, lib/godwoken_explorer/graphql/resolovers/token_approval.ex, lib/godwoken_explorer/graphql/resolovers/token_transfer.ex, lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/graphql/types/account.ex, lib/godwoken_explorer/graphql/types/block.ex, lib/godwoken_explorer/graphql/types/polyjuice.ex, lib/godwoken_explorer/graphql/types/token_approval.ex, lib/godwoken_explorer/graphql/types/token_transfer.ex, lib/godwoken_explorer/graphql/types/udt.ex, lib/godwoken_explorer/token_approval.ex, lib/godwoken_explorer/token_instance.ex, lib/godwoken_explorer/token_transfer.ex, lib/godwoken_indexer/worker/erc721_erc1155_instance_metadata.ex, lib/godwoken_indexer/worker/token_instance_retries_worker.ex, test/factories/token_instance_factory.ex, test/graphql/block_test.exs
link issue: #1184 
- block object
- account
- polyjuice_creator object 
- created_account
- smart_contract object 
- account
- ckb_balance
- token_approval object 
- block
- udt
- token_transfer object 
- from_account
- to_account
- udt
- block
- transaction
- udt object 
- udt/erc721_1155_common_udt(account)
- erc721_erc1155_holder_item(account)
- erc721_erc1155_common_user_token(token_instrance)
- erc721_user_token/erc1155_user_token(udt)
- udt(account)
- unit test
- none
=> feat: optimize grapqhl api with dataloader and batching query (Issue 1184)

lib/godwoken_explorer/account_udt.ex
Filter 0 balance data
- unit test
- none
=> fix: filter 0 balance data

config/config.exs, lib/godwoken_indexer/worker/clean_failed_pending_transactions.ex, test/godwoken_indexer/worker/clean_failed_pending_transactions_test.exs
Check failed pending transactions and delete them
- unit test
- none
=> Issue 1248

lib/godwoken_explorer/graphql/resolovers/udt.ex
YOK price from CMP is incorrect, so filter them temprorary
- unit test
- none
=> fix: filter YOK exchange_rate temporary

lib/godwoken_explorer/graphql/resolovers/udt.ex
=> fix: filter KOI exchange_rate temporary

lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/udt.ex, lib/godwoken_explorer_web/templates/admin/udt/form.html.eex, lib/godwoken_explorer_web/views/udt_view.ex, priv/repo/migrations/20230110060557_add_is_fetch_exchange_rate_to_udt.exs, test/godwoken_explorer_web/controllers/api/udt_controller_test.exs, test/graphql/udt_test.exs
Some udt use same symbol in CMP.So we need to manual control them to fetch exchange rate.
- unit test
- none
=> Issue 1260 3

.github/workflows/clean_cache.yml
clean github action cache when issue closed
- unit test
- none
=> chore: clean github action cache when issue closed

lib/godwoken_explorer/address.ex
If insert same address multiple times once will caused error.So ignore this error.
- none
- none
=> fix: insert address on conflict case nothing

lib/godwoken_indexer/block/bind_l1_l2_worker.ex
RPC may failed, so return nil instead of error
- none
- none
=> fix: when rpc failed return nil

lib/godwoken_explorer_web/router.ex
=> feat: change_graphql_level

lib/godwoken_indexer/block/sync_worker.ex, test/godwoken_indexer/block/sync_worker_test.exs
Update ckb balance of transaction's sender and receiver every time
- unit test
- none
=> feat: transaction's from and to address all need to update ckb balance

lib/godwoken_explorer/graphql/resolovers/account_udt.ex, test/graphql/account_udt_test.exs
=> fix: fix account_udt ignore zore value record

lib/godwoken_explorer/graphql/resolovers/history.ex, lib/godwoken_explorer/graphql/types/history.ex, test/graphql/history_test.exs
issue link: #1294 
- check history api with ckb token
- unit test
- none
=> Issue 1294

coveralls.json
Skip somew coveralls file
- unit test
- none
=> chore: config coverage skip files

lib/godwoken_explorer/graphql/resolovers/udt.ex, test/graphql/udt_test.exs
issue #1286
fix user_erc721_assets show zero value nft
- check user_erc721_assets return noraml
- unit test
- none
=> Issue 1286

config/test.exs, lib/godwoken_explorer/account.ex, lib/godwoken_explorer/block.ex, lib/godwoken_indexer/block/bind_l1_l2_worker.ex, lib/godwoken_indexer/block/global_state_worker.ex, lib/godwoken_indexer/block/sync_l1_block_worker.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/godwoken_rpc.ex, test/factories/account_factory.ex, test/factories/check_info_factory.ex, test/godwoken_explorer/account_test.exs, test/godwoken_indexer/block/bind_l1_l2_worker_test.exs, test/godwoken_indexer/block/global_state_worker_test.exs, test/godwoken_indexer/block/pending_transaction_worker_test.exs, test/godwoken_indexer/block/sync_l1_block_worker_test.exs, test/godwoken_indexer/block/sync_worker_test.exs, test/support/data_case.ex, test/support/factory.ex
Enhande test for sync worker
- unit test
- none
=> Issue 1338

.iex.exs, lib/godwoken_explorer/erc721_token.ex, lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/mix/tasks/update_erc721_token.ex, priv/repo/migrations/20230301032448_create_erc721_tokens.exs, priv/repo/migrations/20230304041045_alter_erc721_tokens.exs, test/factories/erc721_token_factory.ex, test/factories/token_transfer_factory.ex, test/factories/util_factory.ex, test/godwoken_indexer/block/sync_update_erc721_token_test.exs, test/graphql/udt_test.exs, test/support/factory.ex
this pr depend on: https://github.com/Magickbase/godwoken_explorer/pull/1345
issue: #1286 
fix user_erc721_assets api returning burnt nft
- check user_erc721_assets api
- unit test
- none
=> Issue 1286 2

.github/workflows/clean_cache.yml
=> Update cache clean flow

.github/workflows/clean_cache.yml
Fix `Error: Resource not accessible by integration` when running workflow
- unit test
- none
=> chore: update github clean cache workflow

lib/godwoken_explorer/graphql/resolovers/udt.ex, test/graphql/udt_test.exs
issue #1377 
use erc721 token table refactor erc721_inventory api
- unit test
- none
=> fix: fix erc721 inventory with erc721 token table

.iex.exs, lib/godwoken_indexer/block/sync_worker.ex, lib/mix/tasks/update_erc721_token.ex, test/godwoken_indexer/block/sync_update_erc721_token_test.exs
issue: #1286 
**need process history data**
- erc721 inventory
- erc721 holders
- erc721 udts
- unit test
- none
=> fix: fix sync update erc721_token table

lib/godwoken_explorer/graphql/resolovers/udt.ex, test/graphql/udt_test.exs
#1380 
- erc721 inventory api with token id
- unit test
- none
=> hotfix: fix erc721 inventory where conditon with dynamic Issue 1380

config/config.exs, lib/godwoken_indexer/worker/clean_versions.ex, test/factories/version_factory.ex, test/godwoken_indexer/worker/clean_versions_test.exs, test/support/factory.ex
=> Issue 1376

test/godwoken_indexer/worker/clean_versions_test.exs
Fix test file name typo
- unit test
- none
=> test: fix name typo

lib/godwoken_explorer/graphql/sourcify.ex, lib/godwoken_explorer/graphql/sourcify_export.ex, lib/godwoken_explorer/graphql/types/smart_contract.ex, lib/godwoken_explorer/smart_contract.ex, lib/mix/tasks/update_sourcify_metadata.ex, priv/repo/migrations/20230320021530_alter_smart_contract_for_sources.exs, test/graphql/smart_contract_test.exs
issue: #1330 
- add sourcify metadata for smart contract
- fix sourcify process worker
- add new field sourcify metadata of  smart contract object 
- add testing code
- add history process task
- smart contract with sourcify metadate
- history data was process
- auto worker process correct when smart contract register
- unit test
- none
=> Issue 1330

lib/godwoken_explorer/counters/address_token_transfers_counter.ex, lib/godwoken_explorer/graphql/dataloader/batch_polyjuice.ex, lib/godwoken_explorer/graphql/dataloader/batch_udt.ex, lib/godwoken_explorer/graphql/dataloader/smart_contract.ex
link issue #1410 
- check transaction count after erc20 token transfer
- unit test
- none
=> fix: add more async trigger point of account transaction count(issue 1410)

lib/godwoken_explorer/counters/address_token_transfers_counter.ex, lib/godwoken_explorer/graphql/dataloader/batch_polyjuice.ex, lib/godwoken_explorer/graphql/dataloader/batch_udt.ex, lib/godwoken_explorer/graphql/dataloader/smart_contract.ex
link #1410 
- unit test
- none
=> Issue 1410

lib/godwoken_explorer/token/instance_metadata_retriever.ex
issue #1419 
need process history data
- unit test
- none
=> fix: add metadata support erc1155 token instance

lib/godwoken_indexer/worker/generate_yok_series_contract.ex
=> fix: eth_call returns interger

lib/godwoken_indexer/block/pending_transaction_worker.ex, test/godwoken_indexer/block/pending_transaction_worker_test.exs
Fetch from mempool 's transaction's raw may be nil.We need to handle this situation.
- unit test
- none
=> feat: mempool transaction's tx raw may be nil

lib/godwoken_explorer_web/controllers/api/account_udt_controller.ex, test/godwoken_explorer_web/controllers/api/account_udt_controller_test.exs
Support account udt's query by udt contract address hash
- unit test
- none
=> Issue 1340

test/graphql/sourcify_test.exs
@zmcNotafraid  add mock test for sourcify http call
- check github ci succeed
- unit test
- none
=> test: add mock test for sourcify http call

lib/godwoken_indexer/block/pending_transaction_worker.ex, test/godwoken_indexer/block/pending_transaction_worker_test.exs
=> feat: pending transaction needs to store eth tx hash

config/config.exs, lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_explorer/transaction.ex
=> Issue 1437

lib/godwoken_explorer/application.ex, lib/godwoken_explorer/chain.ex, lib/godwoken_explorer/chain/cache/block_count.ex, lib/godwoken_explorer_web/views/block_view.ex, test/godwoken_explorer_web/controllers/api/home_controller_test.exs
All blocks api query is slowly.So we enhance it.
- unit test
- none
=> feat: all blocks api paginator query count is slowly

lib/godwoken_explorer/block.ex, lib/godwoken_explorer/transaction.ex, lib/godwoken_explorer_web/controllers/api/block_controller.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_rpc/util.ex
Display block's timestamp 
- unit test
- none
=> feat: display block's timestamp

lib/godwoken_explorer/chain/cache/transactions.ex, lib/godwoken_indexer/block/sync_worker.ex
=> fix: returning tx timestamp for cache

lib/godwoken_explorer/chain/cache/transactions.ex
=> fix: transactions cache

lib/godwoken_explorer/token_transfer.ex, lib/godwoken_indexer/transform/token_transfers.ex
When user deposit or withdraw use erc20 contract, we need to update token balance
- unit test
- none
=> Issue 1475

docker/Dockerfile
=> chore: remove glibc

.github/workflows/build.yml
=> PrintImageFullNameInfo

config/config.exs
=> chore: start TokenInstanceRetriesWorker

lib/godwoken_explorer/exchange_rates/source/coin_market_cap.ex, lib/godwoken_explorer/graphql/resolovers/udt.ex
If coinmarketcap can't fetch price, returns 0 as default.
- unit test
- none
=> Fix exchange rate
