lib/godwoken_indexer/block/bind_l1_l2_worker.ex
充值到layer2 太慢，所以这里减少每次获取的间隔，增大每次获取块数量的数据
=> feat: reduct deposition block number to tip block range

priv/repo/migrations/20220307032631_remove_block_number_index.exs
sort use block_number index is slow
=> feat: remove block_number index for transactions

lib/godwoken_explorer/account_udt.ex, lib/godwoken_explorer_web/views/udt_view.ex, lib/godwoken_indexer/worker/refresh_udt_supply.ex
因为 eth_call total_supply 返回的supply 是没有经过decimal 处理的，所以默认supply 都是不处理
=> feat: save supply with no decimal

lib/godwoken_explorer/token_transfer.ex
加上log index 的排序会变慢，参考blockscout 只需要block number 排序
=> feat: remove sort by log_index

lib/godwoken_indexer/block/sync_worker.ex
When we fetch multiple block together, we need to uniq the last block's data
=> fix: sort by block_number first

docs/api/deposit_history.md, docs/api/withdrawal_request.md, docs/schema.graphql, lib/godwoken_explorer/account.ex, lib/godwoken_explorer/graphql/resolovers/account_udt.ex, lib/godwoken_explorer/graphql/types/block.ex, lib/godwoken_explorer/graphql/types/udt.ex, lib/godwoken_explorer_web/controllers/api/transfer_controller.ex, lib/godwoken_explorer_web/controllers/api/udt_controller.ex, lib/godwoken_explorer_web/views/smart_contract_view.ex, lib/godwoken_explorer_web/views/udt_view.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_indexer/worker/check_contract_code.ex, lib/godwoken_rpc/receipt.ex
1. registry_address 只有在使用 fetch_balances 的时候才使用。
2. account_udt 里的token_contract_address_hash 只可能是account 的 script_hash 或者 eth_address. 当这个token 是bridge的时候，是script_hash, 是合约的时候是eth_address
3. account  是 :eth_user 和 :polyjuice_contract 的时候展示 eth_address, 其余的时候展示script_hash, registry_addresss  不会展示
=> fix: account_udt not use registry_address

.github/ISSUE_TEMPLATE/register-a-general-contract.yml, .github/ISSUE_TEMPLATE/register-a-new-bridged-token.yml, .github/ISSUE_TEMPLATE/register-a-new-native-erc20-token.yml
Mark some textareas `render: shell` so the contents will be formatted into code fragments instead of plain texts.
=> chore: refine issue templates

.github/ISSUE_TEMPLATE/register-a-new-native-erc20-token.yml
There could be some native erc20 tokens bridged from other chains and `UAN` is necessary in these cases, but it's not mandatory for tokens not bridged from otherwhere.
=> fix: add uan field in native erc20 token form

lib/godwoken_explorer/account/current_bridged_udt_balance.ex, lib/godwoken_explorer/account/current_udt_balance.ex, lib/godwoken_explorer/graphql/resolovers/account_udt.ex, lib/godwoken_explorer/graphql/types/account_udt.ex, lib/godwoken_explorer/graphql/types/udt.ex, test/graphql/account_test.exs, test/graphql/account_udt_test.exs
summary:
if checking address had some token which type is the bridge(and its mapping native token was exist), will return both native token and bridge token, and their balance values will be the same
env:  testnet-stg   
error example:
expect example:
```graphql
query {
account_udts(
input: { address_hashes: ["0x2454851a9320a0e11a3dd27f0d3585158ea84c94"] }
) {
udt_script_hash
value
uniq_id
udt {
id
type
name
bridge_account_id
script_hash
decimal
value
}
account {
id
eth_address
script_hash
}
}
}
```
result:
```graphql
{
"data": {
"account_udts": [
{
"account": {
"eth_address": null,
"id": 29407,
"script_hash": "0x454843ef13a5c57f97270b50bc49ef2d12e35fb7e72a145b0909ba65a5f9bfdd"
},
"udt": {
"bridge_account_id": 40446,
"decimal": null,
"id": "29407",
"name": "USDC (via ForceBridge from …
```
=> Fix: fix issue 801 account udts return with native and bridge token

docs/schema.graphql, lib/godwoken_explorer/graphql/resolovers/udt.ex, lib/godwoken_explorer/graphql/types/udt.ex, test/graphql/udt_test.exs
add new query condition for `udt` query
example:
```graphql
query {
udt(
input: {
id: 36050
contract_address: "0x2275AFE815DE66BEABE7A2C03005537AB843AFB2"
}
) {
id
bridge_account_id
name
script_hash
contract_address_hash
}
}
```
result: 
```graphql
{
"data": {
"udt": {
"bridge_account_id": null,
"contract_address_hash": "0x2275afe815de66beabe7a2c03005537ab843afb2",
"id": "36050",
"name": "GodwokenToken on testnet_v1",
"script_hash": null
}
}
}
```
=> (graphql) Feat: enhancement for issue 823, add query condition for udt

lib/godwoken_explorer/graphql/middleware/null_filter.ex, lib/godwoken_explorer/graphql/resolovers/token_transfer.ex, lib/godwoken_explorer/graphql/types/token_transfer.ex, test/graphql/token_transfers_test.exs
summary:
API server raise internal error when using explicit null value of input fields
env: testnet-stg
error example:
```
query {
token_transfers(
input: {
before: null
after: null
token_contract_address_hash: null
limit: 1
}
) {
entries {
amount
transaction_hash
log_index
polyjuice {
status
}
from_address
to_address
block {
number
timestamp
status
}
udt {
id
decimal
symbol
}
}
metadata {
total_count
before
after
}
}
}
```
error result: 
after fix will return:
```
{
"data": {
"token_transfers": {
"entries": [
{
"amount": "5000000000000000000",
"block": {
"number": 250777,
"status": "COMMITTED",
"timestamp": "2022-08-04T12:39:03.500000Z"
},
"from_address": "0x19884aec2e463c06f08c3f380568d1a531d3293b",
"log_index": 0,
"polyjuice": {
"status": "SUCCEED"
},
"to_address": …
```
=> (graphql) fix issue 827 of filtering unexpect null value for query

lib/godwoken_explorer/graphql/sourcify.ex, lib/godwoken_explorer/smart_contract.ex, priv/repo/migrations/20220825070147_alter_smart_contracts_null_requrie_field.exs, test/graphql/sourcify_test.exs
fields with `name`, `abi` and `source code` is required by insert or update to the repo.
so if the smart contract not registered in the sourcify then we can not get the data when insert/update the smart contract with orther fields like `deployment tx hash`
solution:
we add the default value for the require fields
=> Fix: fix unregistered smart contact update other data

lib/godwoken_explorer/chain/cache/poly_version.ex, lib/godwoken_explorer_web/controllers/admin/dashboard_controller.ex, lib/godwoken_explorer_web/router.ex, lib/godwoken_explorer_web/templates/admin/dashboard/index.html.eex, lib/godwoken_explorer_web/views/admin/dashboard_view.ex
当前的封装的缓存模块没办法在部署后删掉已经存在的cache，由于更新version 的频率很低，所以在后台增加一个功能手动去删除。
=> feat: flush poly version cache in admin

lib/godwoken_explorer/graphql/sourcify.ex
link issue https://github.com/Magickbase/godwoken_explorer/issues/918
=> BUG: Hot Fix smart contract nil field update replace existed value

lib/godwoken_explorer/graphql/resolovers/account_udt.ex, test/graphql/account_udt_test.exs
elixir Enum.sort_by default sorter `asc` and `desc`  which is a convenience for [`&<=/2`](https://hexdocs.pm/elixir/1.13/Kernel.html#%3C=/2) and [`&>=/2`](https://hexdocs.pm/elixir/1.13/Kernel.html#%3E=/2) respectively. 
in erlang world ,all of `term` is comparable
In this pr scenario, we need compare `updated_at` field by sorting return data and distinct it.
but the `DateTime` compare with default sorter not return correct result
it cause some error like this
```
iex(1)> ~U[2022-07-25 07:53:57.788000Z] > ~U[2022-09-07 10:34:14.021000Z]
true
iex(2)> DateTime.utc_now
~U[2022-09-17 04:00:49.814911Z]
iex(3)> ~U[2022-09-17 04:00:49.814911Z] > ~U[2022-09-07 10:34:14.021000Z]
true
```
so we need add a custom sorter to replace the default sorter `asc/desc` by using `DateTime` compare function …
=> HotFix: fix compare function for DateTime type

lib/godwoken_explorer/graphql/resolovers/transaction.ex, lib/godwoken_explorer/graphql/utils.ex, test/graphql/transaction_test.exs
problem:
when use calling the transcation api with sorter `[:block_number]` the paginator may return unexpect results with duplicate value of previous page.
this pr solve:
add default implicit unique sorter feilds for paginator to comfirm the returning cursor‘s uniqueness
example:
if call transaction api with sorter [:block_number],we will change it to [:block_number, :hash] to comfirm the uniqueness
=> Fix: add default uniq cursor fields for transction api

lib/godwoken_explorer/graphql/resolovers/udt.ex, test/graphql/udt_test.exs
problem:
erc1155 inventory was setting error cursor fields that returning unexpect results when using `after` cursor for next page
solve:
add `token_id` for cursor fields and it's mapping order by fields to fixed
=> Fix: fix erc1155 inventory paginator cursor fields

lib/godwoken_explorer/account.ex, lib/godwoken_indexer/block/sync_l1_block_worker.ex, lib/godwoken_indexer/block/sync_worker.ex, test/godwoken_explorer/account_test.exs
We can get account code_hash hash_type and args  from polyjuice creator transaction's info.So we can create account with these info. 
- unit test
- none
=> feat: auto create account from polyjuice creator transaction

docs/schema.graphql, lib/godwoken_explorer/graphql/types/udt.ex, test/graphql/udt_test.exs
https://github.com/Magickbase/godwoken_explorer/issues/1034
Token name is missing when calling the user721_asserts api with `udt` subfield object 
use incorrect object for user721_asserts `udt` subfield 
must use `erc721_1155_common_udt` object
stg env example
```graphql
query {
user_erc721_assets(
input: {
user_address: "0x0000000000ce6d8c1fba76f26d6cc5db71432710"
limit: 1
}
) {
entries {
token_id
address_hash
token_contract_address_hash
value
udt {
id
name
}
}
metadata {
total_count
after
before
}
}
}
```
result
```
{
"data": {
"user_erc721_assets": {
"entries": [
{
"address_hash": "0x0000000000ce6d8c1fba76f26d6cc5db71432710",
"token_contract_address_hash": "0x76ef87aaaa9213b1e7f96460e23bd9d0b7dbcc64",
"token_id": "812",
"udt": {
"id": 70030,
"name": "NervosPunkz"
},
"value": "1"
}
], …
```
=> HotFix: fix user 721 assert api subfield udt return object

lib/godwoken_rpc/transaction.ex, lib/godwoken_rpc/util.ex, test/godwoken_rpc/util_test.exs
When polyjuice args input_size is 0, we need to check that args length is 144.Only in this cause, it is a native transfer transaction.
- none
=> Issue 1032 2

lib/godwoken_explorer_web/views/error_view.ex
Some robot will test api's not exist route, so will generate a lot of error logs of tempate_not_found.
- none
- none
=> feat: template not found

.github/workflows/codeql-analysis.yml
This commit removes codeql for ruby because all ruby codes have been removed by https://github.com/Magickbase/godwoken_explorer/pull/1058 which introduced a blame that no source code is found
Ref: https://github.com/Magickbase/godwoken_explorer/actions/runs/3213239075/jobs/5252762510
- none
- none
=> ci: remove codeql for ruby

lib/godwoken_rpc/block.ex
From our error logs, we found that eth_block_by_hash rpc have big probability to failed.Although our sync worker will retry and can keep data correct.But it will generate a lot of error log.
So in first step, we add retry for this rpc fetch every 5 seconds and keep watching for these logs 
- none
- none
=> feat: retry for rpc eth_block_by_hash

lib/godwoken_explorer/counters/average_block_time.ex
calculate average block time with 12 block's timestamp is not precise, so increase to 24
- none
- none
=> chore: increase block count to calculate average block time

lib/godwoken_explorer/graphql/resolovers/udt.ex, test/graphql/udt_test.exs
link issue: #1072
1. fix raise internal erroc when call `udt` api by using nonexist address  
```graphql
query {
udt(
input: { contract_address: "0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c" }
) {
contract_address_hash
symbol
name
}
}
{
"data": {
"udt": {
"contract_address_hash": "0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c",
"name": null,
"symbol": null
}
}
}
query {
udt(
input: { contract_address: "0xeeb92d6b3999abdc8cc0226069d88c07f241fd4e" }
) {
contract_address_hash
symbol
name
}
}
{
"data": {
"udt": null
}
}
```
- unit test
- none
=> HotFix: fix udt api raise error when input not exist address

lib/godwoken_explorer/account/current_udt_balance.ex, lib/godwoken_explorer/counters/average_block_time.ex
Datetime type data can't directly use default sort_by, it must use `DateTime.compare/2` function to compare
- none
- none
=> fix: datetime sort_by must use  to compare

lib/godwoken_indexer/block/sync_worker.ex
When we create udt,we need to find it's relationship of account.But account may not exist at this time, so we need to create account first.
- none
- none
=> feat: create udt account before create udt

lib/godwoken_explorer/token/metadata_retriever.ex, lib/godwoken_explorer/udt.ex, lib/godwoken_indexer/block/sync_worker.ex, lib/godwoken_indexer/worker/check_contract_udt.ex, test/factories/account_factory.ex, test/godwoken_indexer/worker/check_contract_udt_test.exs
When a new contract deployed, we can verify it is a udt or not.
For erc20, read the contract method of name,symbol, total_supply, decimal.
For erc721 and erc1155, then stand by [erc165](https://eips.ethereum.org/EIPS/eip-165) interface.
At last, compare with exist contract code and create smart contract if possibly.
- unit test
- none
=> Issue 1079 2

lib/godwoken_explorer/account.ex, lib/godwoken_explorer/graphql/resolovers/transaction.ex, test/graphql/transaction_test.exs
issue link: #1102
fix transactions query with script hash input fields which cause by mapping error fields 
1. check transaction api with from/to script hash
2. check transaction api with from/to eth hash
- unit test
- none
=> Fix: fix call transactions with script hash input field raise error

lib/godwoken_explorer/graphql/resolovers/common.ex, lib/godwoken_explorer/graphql/resolovers/udt.ex, test/factories/current_udt_balance_factory.ex, test/factories/token_transfer_factory.ex, test/graphql/smart_contract_test.exs, test/graphql/token_approvals_test.exs, test/graphql/token_transfer_test.exs, test/graphql/transaction_test.exs, test/graphql/udt_test.exs
link: #993
fix cursor pagination with first page not fillfull error if it has enough data
- transactions with pagination
- smart_contracts with pagination
- token_approvals with pagination
- erc20/erc721/erc1155 token_transfers with pagination
- user_erc721_asserts/user_erc1155_asserts with pagination
- udts/erc721udts/erc1155udts with pagination
- erc721holders/erc1155holders with pagination
- erc721inventory/erc1155inventory with pagination
- erc1155userinventory with pagination
- none
=> Fix: fix cursor pagination with first page not fillfull error if it has enough data

lib/godwoken_explorer/block.ex
Query blocks table often timeout.So add option to avoid it.
- none
- none
=> feat: set timeout infinity to avoid query timeout

lib/godwoken_explorer/account.ex, lib/godwoken_indexer/worker/import_contract_code.ex, lib/godwoken_indexer/worker/sourcify.ex, test/godwoken_explorer/account_test.exs
Zero nonce eoa user can transfer to contract account in godwoken, but contract account use eoa user's eth_address.We need to keep uniq eth_address in our database, so remove eoa user's eth_address when we found this situation.
- unit test
- none
=> feat: hanle eoa transfer to contract account

lib/godwoken_explorer/udt.ex, test/godwoken_explorer/udt_test.exs
=> fix: erc20 udt return no minted_count

lib/godwoken_explorer/account_udt.ex
Keep account's bridge udt and native udt record to next uniq.
- unit test
- none
=> fix: keep all account_udt to next uniq operation

config/config.exs, lib/godwoken_explorer/application.ex, lib/godwoken_explorer/bit/api.ex, lib/godwoken_explorer/graphql/resolovers/search.ex, lib/godwoken_explorer/graphql/types/search.ex, mix.exs, test/godwoken_explorer/bit/api_test.exs, test/graphql/search_test.exs
issue link: #1288 
feat: add batch bit api for search bit_alias mapping address and it's reverse api
- search_bit_alias graphql api
- reverse_search_bit_alias graphql api
- batch_fetch_addresses_by_aliases graphql api
- batch_fetch_aliases_by_addresses graphql api
- unit test
- none
=> feat: add bit_alias batch api

lib/godwoken_explorer/graphql/resolovers/smart_contract.ex, lib/godwoken_explorer/graphql/types/smart_contract.ex, lib/godwoken_explorer/graphql/types/udt.ex, lib/godwoken_explorer/smart_contract.ex, test/graphql/smart_contract_test.exs
issue: #1300 
- unit test
- none
=> fix smart  contracts api raise with nil sort type

lib/godwoken_explorer/token_transfer.ex
Snapshot erc721 token
- unit test
- none
=>  feat: snapshot erc721 token and return owner address
